# This profile is activated when running inside the Docker container!
spring.config.activate.on-profile=docker

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.generate-ddl=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/bandstoredb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bandstoredb123postgres}

# JWT Security Settings
application.security.jwt.secret-key=${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}