spring.application.name=backend

# Backend port
server.port=8080

# Database Config
# Local Spring Boot Profile
spring.datasource.url=jdbc:postgresql://localhost:5432/bandstoredb
spring.datasource.username=postgres
spring.datasource.password=bandstoredb123postgres

# JPA Settings
# The line below tells Hibernate to check the existing schema against my @Entity classes, but not to change it.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# application-local.properties
debug=true
# OR
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicExtractor=TRACE

# JWT Security Settings
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000