# This profile is activated when using Azure!
spring.config.activate.on-profile=prod

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY}
application.security.jwt.expiration=${APPLICATION_SECURITY_JWT_EXPIRATION:86400000}