# This profile is activated when running inside the Docker container!

spring.config.activate.on-profile=docker

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/bandstoredb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bandstoredb123postgres}